### ISSUE TITLE
result.catch is not a function

### ISSUE THREAD

**Issue by bhj** [jcoreio/async-throttle#11]
Hi again,

Starting with 1.3.0 I'm getting this error with each throttled call:

```
  <rejected> TypeError: result.catch is not a function
      at invoke (.../node_modules/@jcoreio/async-throttle/index.js:100:31)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

My [usage](https://github.com/bhj/karaoke-forever/blob/master/server/Library/ipc.js#L13) hasn't changed and 1.2.0 and earlier work fine... maybe a check just needs to be added there? Thanks for taking a look!

**Comment by neversun** [comment]
I had the exakt same issues when not providing an async function to throttle. For me, the following line is failing https://github.com/jcoreio/async-throttle/blob/947f638bc9e55437e234e221bab97266b8ff045f/src/index.js#L59

Are you sure you are passing a promise?

**Comment by jedwards1211** [comment]
Eep sorry for the delay.  Yes, I need to change it to support sync functions.

**Comment by bhj** [comment]
@neversun Thanks, indeed it was once async then has been sync since moving to a forked process.

@jedwards1211 Awesome, thanks as usual :)
