### ISSUE TITLE
Doesn't work, error async_throttle_1.throttle is not a function

### ISSUE THREAD

**Issue by kolnogorov** [jcoreio/async-throttle#14]
Every time i try to call throttle like it said in example, it throws an error:
```
Uncaught (in promise) TypeError: async_throttle_1.throttle is not a function
```

**Comment by jedwards1211** [comment]
I added an example of `import throttle from '@jcoreio/async-throttle'` (instead of `import {throttle}` to the readme, sorry if that was confusing!
