### ISSUE TITLE
Remove Babel requirement?

### ISSUE THREAD

**Issue by bhj** [jcoreio/async-throttle#3]
Hey again :)

I [recently switched](https://github.com/bhj/karaoke-forever/commit/17989f28ea9c9d34a4f12ebd949252263b3626e3) to the official npm module, but since Babel isn't used server-side in this case, I get errors like

```
  <rejected> Error: Cannot find module 'babel-runtime/regenerator'
  Require stack:
  - C:\Users\Me\AppData\Roaming\npm\node_modules\karaoke-forever\node_modules\@jcoreio\async-throttle\lib\index.js
  - C:\Users\Me\AppData\Roaming\npm\node_modules\karaoke-forever\server\Library\ipc.js
  - C:\Users\Me\AppData\Roaming\npm\node_modules\karaoke-forever\server\serverWorker.js
  - C:\Users\Me\AppData\Roaming\npm\node_modules\karaoke-forever\server\main.js
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
      at Function.Module._load (internal/modules/cjs/loader.js:841:27)
      at Module.require (internal/modules/cjs/loader.js:1025:19)
      at require (internal/modules/cjs/helpers.js:72:18)
      at Object.<anonymous> (C:\Users\Me\AppData\Roaming\npm\node_modules\karaoke-forever\node_modules\@jcoreio\async-throttle\lib\index.js:3:20)
      at Module._compile (internal/modules/cjs/loader.js:1137:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
      at Module.load (internal/modules/cjs/loader.js:985:32)
      at Function.Module._load (internal/modules/cjs/loader.js:878:14)
      at Module.require (internal/modules/cjs/loader.js:1025:19) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      'C:\\Users\\Me\\AppData\\Roaming\\npm\\node_modules\\karaoke-forever\\node_modules\\@jcoreio\\async-throttle\\lib\\index.js',
      'C:\\Users\\Me\\AppData\\Roaming\\npm\\node_modules\\karaoke-forever\\server\\Library\\ipc.js',
      'C:\\Users\\Me\\AppData\\Roaming\\npm\\node_modules\\karaoke-forever\\server\\serverWorker.js',
      'C:\\Users\\Me\\AppData\\Roaming\\npm\\node_modules\\karaoke-forever\\server\\main.js'
    ]
```

FWIW, the src works fine as-is in modern Node versions (minus the type annotations of course) but I'm not sure of other ramifications. Thanks again for this library!

**Comment by jedwards1211** [comment]
Makes sense, yeah I'll remove the requirement hopefully later today, ping me if I forget :P

**Comment by jedwards1211** [comment]
Okay actually it seems that `@babel/preset-env` still applies the regenerator transform for `"targets": {"browsers": "last 2 versions"}` so I'm tempted to keep `@babel/runtime` so that people don't have to go to the trouble of requiring `regenerator-runtime/register` themselves.

Also, the reason you were seeing that error is not because Babel isn't used server-side, it's because the runtime transform was applied to the code but because `babel-register` is in `devDependencies`, I forgot to put it in primary `dependencies`.
Various other packages of mine have `babel-register` in `dependencies` which is why I wasn't getting this error myself.  

So I'll upgrade to the latest `@babel/runtime` and put it in `dependencies`.

**Comment by jedwards1211** [comment]
I guess another option is to use a conditional exports package and tell people to load the polyfills if necessary themselves...I dunno, what do you think?

**Comment by bhj** [comment]
@jedwards1211 Awesome! Figured my PR was opinionated (don't use yarn for example...) but could be a reference. Appreciate the comments and thanks for pushing this out!

**Comment by jedwards1211** [comment]
You're welcome!

**Comment by WofWca** [comment]
It still requires Babel runtime, doesn't it? Looking at [the code on npmjs](https://www.npmjs.com/package/@jcoreio/async-throttle?activeTab=code)

**Comment by jedwards1211** [comment]
@WofWca okay as of 1.6.1 as long as you are using tools that support `module` or `exports` in `package.json`, it should resolve to the ES module that doesn't require `@babel/runtime`.  The package still contains the CJS module which requires `@babel/runtime`, so it depends on whether your tools resolve to the ES or the CJS module.

**Comment by WofWca** [comment]
Thank you very much!
