### ISSUE TITLE
Add cancel/abort.

### ISSUE THREAD

**Issue by satazor** [jcoreio/async-throttle#8]
Similarly to lodash, it would be awesome to have a `cancel` method attached to the returned function.

The implemention would cancel any pending timeout as well as returning a the ongoing promise, so that it can be awaited.

**Comment by jedwards1211** [comment]
yeah that's a good point, I'll work on that!

**Comment by jedwards1211** [comment]
And `flush` too (though unlike sync throttle, it's not possible to immediately invoke the throttled function if an async invocation is in progress)

**Comment by satazor** [comment]
Thank you very much, nice work!
